---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-sep19-confirm1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-sep19-confirm1 
  name: rag-sep19-confirm1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi